/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2018-06-04 02:33:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style>\r\n");
      out.write(".head_meun{\r\n");
      out.write("float: right;\r\n");
      out.write("margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".login{\r\n");
      out.write("\tborder: px solid white;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\ttext-decoration-style: none;\r\n");
      out.write("\tfont-size:px;\r\n");
      out.write("\r\n");
      out.write("\tmargin-right: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<script type= \"text/javascript\" src=\"js/jquery.js\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".mbtn1\").click(function(){\r\n");
      out.write("\t\tlet $clas = $('.class').val();\r\n");
      out.write("\t\tlet $stname = $('.stname').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("            data: {\r\n");
      out.write("            \tcityName : $cityName,\r\n");
      out.write("            \tcityTemp : $cityTemp\r\n");
      out.write("            },\r\n");
      out.write("            url: '/preWeather/Weather_searche',\r\n");
      out.write("            type:\"post\",\r\n");
      out.write("            dataType: 'JSON',\r\n");
      out.write("            success: function(data){\r\n");
      out.write("                console.log(data);\r\n");
      out.write("            },\r\n");
      out.write("            error: function(textStatus){\r\n");
      out.write("                console.log('error ' + textStatus );\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t})\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<title>天气预报小项目检验</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Simple Metro Weather Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"js/jquery-2.2.3.min.js\"></script> \r\n");
      out.write("<!-- //js --> \r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<link href=\"css/owl.carousel.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=cyrillic,cyrillic-ext,latin-ext\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"head_meun\">\r\n");
      out.write("<a href=\"frontweb/web/login.html\" class=\"login\"><li>登录<span>|</span></li></a>\r\n");
      out.write("<a href=\"frontweb/web/register.html\" class=\"login\"><li>注册<span>|</span></li></a>\r\n");
      out.write("<a href=\"\" class=\"login\"><li>关于我们</li></a>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<h1>天气预报小程序</h1>\r\n");
      out.write("\t\t<div class=\"w3layouts_main_grids\">\r\n");
      out.write("\t\t\t<div class=\"w3layouts_main_grid_left\">\r\n");
      out.write("\t\t\t\t<div class=\"w3_search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"../Weather_search\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"cityName\" placeholder=\"Search...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\" \" >\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"w3l_search_bottom\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"w3ls_weather\">\r\n");
      out.write("\t\t\t\t\t\t<li><i>7:00 AM</i><a href='../ReturnPictureUrl?cityName=American'>");
      out.print(session.getAttribute("city") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp") );
      out.write("°</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i>8:00 AM</i><a href='../ReturnPictureUrl?cityName=China'>");
      out.print(session.getAttribute("city2") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp2") );
      out.write("°</span></span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i>9:00 PM</i><a href='../ReturnPictureUrl?cityName=Argentina'>");
      out.print(session.getAttribute("city3") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp3") );
      out.write("°</span></span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i>10:00 AM</i><a href='../ReturnPictureUrl?cityName=Australia'>");
      out.print(session.getAttribute("city4") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp4") );
      out.write("°</span></span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i>12:00 PM</i><a href='../ReturnPictureUrl?cityName=Belarus'>");
      out.print(session.getAttribute("city5") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp5") );
      out.write("°</span></span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i>14:00 PM</i><a href='../ReturnPictureUrl?cityName=Chile'>");
      out.print(session.getAttribute("city6") );
      out.write("</a><span>");
      out.print(session.getAttribute("temp6") );
      out.write("°</span></span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"agileits_social_icons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"agileinfo_facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"wthree_instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"w3_agileits_twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"agile_google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3layouts_main_grid_right\">\r\n");
      out.write("\t\t\t\t<div class=\"agileits_w3layouts_main_grid_right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_agile_main_grid_left\">\r\n");
      out.write("\t\t\t\t\t\t<h2>");
      out.print(session.getAttribute("cityNameso") );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t<p><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i>");
      out.print(session.getAttribute("cityTempso") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_agile_main_grid_right \">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/1.jpg\" class=\"imgw3\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"w3layouts_weather_updates\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"clear-day\" width=\"25\" height=\"25\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t25°<span>Monday<i><label class=\"fa fa-clock-o\" aria-hidden=\"true\"></label> 11:00 AM</i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"sleet\" width=\"25\" height=\"25\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t5°<span>Tuesday<i><label class=\"fa fa-clock-o\" aria-hidden=\"true\"></label> 12:00 PM</i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"partly-cloudy-day\" width=\"25\" height=\"25\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t25°<span>Wednesday<i><label class=\"fa fa-clock-o\" aria-hidden=\"true\"></label> 9:00 AM</i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"partly-cloudy-night\" width=\"25\" height=\"25\"> </canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t15°<span>Thursday<i><label class=\"fa fa-clock-o\" aria-hidden=\"true\"></label> 4:00 PM</i></span>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"w3_agile_main_grid_right1\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"owl-demo\" class=\"owl-carousel\"> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"clear-night\" width=\"30\" height=\"30\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title2") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content2") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"cloudy\" width=\"30\" height=\"30\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title3") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content3") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"rain\" width=\"30\" height=\"30\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title4") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content4") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"wind\" width=\"30\" height=\"30\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title5") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content5") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"snow\" width=\"30\" height=\"30\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title6") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content6") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"fog\" width=\"25\" height=\"25\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3_weather_scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("title7") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>");
      out.print(session.getAttribute("content7") );
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<canvas id=\"fog\" width=\"25\" height=\"25\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"agileits_copyright\">\t\t \t\r\n");
      out.write("\t\t\t<p>© 2018 Simple Metro Weather Widget. All Rights Reserved | Design by <a href=\"http://w3layouts.com/\" target=\"_blank\">软件工程</a> </p>\t\t \t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script src=\"js/owl.carousel.js\"></script>  \r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function() { \r\n");
      out.write("\t\t\t\t$(\"#owl-demo\").owlCarousel({\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t  autoPlay: 3000, //Set AutoPlay to 3 seconds\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t  items :5,\r\n");
      out.write("\t\t\t\t  itemsDesktop : [640,5],\r\n");
      out.write("\t\t\t\t  itemsDesktopSmall : [414,2],\r\n");
      out.write("\t\t\t\t  navigation : true\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!--skycons-icons-->\r\n");
      out.write("\t\t\t<script src=\"js/skycons.js\"></script>\r\n");
      out.write("\t\t<!--//skycons-icons-->\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t var icons = new Skycons({\"color\": \"#fff\"}),\r\n");
      out.write("\t\t\t\t  list  = [\r\n");
      out.write("\t\t\t\t\t\"clear-night\",\"wind\",\"rain\",\"cloudy\", \"snow\",\"fog\"\r\n");
      out.write("\t\t\t\t  ],\r\n");
      out.write("\t\t\t\t  i;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  for(i = list.length; i--; )\r\n");
      out.write("\t\t\t\ticons.set(list[i], list[i]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t  icons.play();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t var icons = new Skycons({\"color\": \"#FFD700\"}),\r\n");
      out.write("\t\t\t\t  list  = [\r\n");
      out.write("\t\t\t\t\t\"partly-cloudy-day\",\r\n");
      out.write("\t\t\t\t\t\"partly-cloudy-night\",\"clear-day\",\"sleet\"\r\n");
      out.write("\t\t\t\t  ],\r\n");
      out.write("\t\t\t\t  i;\r\n");
      out.write("\r\n");
      out.write("\t\t\t  for(i = list.length; i--; )\r\n");
      out.write("\t\t\t\ticons.set(list[i], list[i]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t  icons.play();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
